---
# Title of the config
sudo:
# log file to check
- /home/pitserver/doto7679/Documents/sudo.log
# old file to diff against
- /home/pitserver/doto7679/Documents/sudo.log.old
# matcher file to determine what errors should be screened out
- /home/pitserver/doto7679/Documents/logcheck/lib/matchers/sudo.rb

zoomba:
- /home/pitserver/doto7679/Documents/zoomba.log
- /home/pitserver/doto7679/Documents/zoomba.log.old
- /home/pitserver/doto7679/Documents/logcheck/lib/matchers/zoomba.rb
