---
sudo
# The name of the file to check for errors:
- file: /home/pitserver/doto7679/Documents/sudo.log
# The file to check against to see if the error is new:
- oldfile: /home/pitserver/doto7679/Documents/sudo.log.old
# The matcher to remove errors we don't care about:
- matcher: /home/pitserver/doto7679/Documents/logcheck/lib/matchers/sudo.rb

zoomba
- file: /home/pitserver/doto7679/Documents/zoomba.log
- oldfile: /home/pitserver/doto7679/Documents/zoomba.log.old
- matcher: /home/pitserver/doto7679/Documents/logcheck/lib/matchers/zoomba.rb
